info:
  contact: {}
paths:
  /api/v1/chart/profit:
    get:
      parameters:
      - description: the duration to query-{7D,1M,1Y}
        in: query
        name: range
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: the [(timetsamp,profit)] in the time range
      summary: get the phased profit info
  /api/v1/chart/ratio:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: amount of each asset in usd
      summary: get the ratio info
  /api/v1/chart/volume:
    get:
      parameters:
      - description: the duration to query-{7D,1M,1Y}
        in: query
        name: range
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: the [(timestamp,volume)] in the time range
      summary: get the total volume info
  /api/v1/price_info/{coin_ids}:
    get:
      parameters:
      - description: '{BTC,ETH,USDT,HT,MDX}'
        in: path
        name: coin_ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'the price trend of coin, {"rate": ..., "trend": ...}'
  /api/v1/transaction/{address}:
    get:
      parameters:
      - description: user account address
        in: path
        name: address
        required: true
        type: string
      - description: tag of the transaction-{deposit,withdraw,claimProfit}, if not
          specify, get all the category
        in: query
        name: tag
        type: string
      - description: index of page
        in: query
        name: page
        required: true
        type: integer
      - description: size of each page
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: the transaction of the page
      summary: get the transaction info
swagger: "2.0"
