basePath: /api/v1
info:
  contact: {}
  description: API to interact with the pick finance backend
  title: pick finance api
  version: 0.0.1
paths:
  /chart/profit:
    get:
      description: gets the profit in a time range
      parameters:
      - description: the duration to query-{7D,1M,1Y}
        in: query
        name: range
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: the [(timestamp,profit)] in the time range
      summary: get the phased profit info
  /chart/ratio:
    get:
      description: gets the ratio of each asset info
      produces:
      - application/json
      responses:
        "200":
          description: amount of each asset in usd
      summary: get the ratio info
  /chart/volume:
    get:
      description: gets the volume of each asset in usd, and the start of the query
        timestamp
      parameters:
      - description: the duration to query-{7D,1M,1Y}
        in: query
        name: range
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'the {startTime: ..., volume: ...} in the time range'
      summary: get the total volume info
  /notification:
    get:
      description: obtains the specific notification by the tag
      parameters:
      - description: tag of the notification-{QuotaUpdate,Activity,Weekly}, if not
          specify, get all the category
        in: query
        name: tag
        type: string
      - description: index of page
        in: query
        name: page
        required: true
        type: integer
      - description: size of each page
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: array of notification
      summary: get notification info
    post:
      description: publish new notification with title, content, category
      parameters:
      - description: the hash of specific information to sign
        in: formData
        name: raw_data
        required: true
        type: string
      - description: the signature of the raw_data by the publisher
        in: formData
        name: signature
        required: true
        type: string
      - description: the title of the notification
        in: formData
        name: title
        required: true
        type: string
      - description: the content of the notification
        in: formData
        name: content
        required: true
        type: string
      - description: 'the category of the notification: { QuotaUpdate, Weekly, Activity}'
        in: formData
        name: tag
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: publish new notification
  /price_info/{coin}:
    get:
      description: gets the Coin Price info and trend
      parameters:
      - description: '{BTC,ETH,USDT,HT,MDX}'
        in: path
        name: coin
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'the price trend of coin, {trend_info:{"rate": ..., "trend":
            ...}}'
      summary: get the Coin Price info and trend
  /transaction/{address}:
    get:
      description: gets the history transaction of specific account
      parameters:
      - description: user account address
        in: path
        name: address
        required: true
        type: string
      - description: tag of the transaction-{deposit,withdraw,claimProfit}, if not
          specify, get all the category
        in: query
        name: tag
        type: string
      - description: index of page
        in: query
        name: page
        required: true
        type: integer
      - description: size of each page
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: a page of transaction and the total transaction amount-{"transactions
        "400":
          description: invalid params
        "500":
          description: server error
      summary: get the transaction info
swagger: "2.0"
